[package]
name = "cerberus"
version = "0.1.0"
edition = "2024"
description = "A system integrity checker that unlocks a LUKS-encrypted disk when the integrity of the system is verified."

[dependencies]
notify = "8.0.0"
sha2 = "0.10.9"
