all:
  vars:
    sudo_user: unitel
    sudo_user_public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICHAWq/N8I40Ng6j3z55QtrP00LQzYcPlxuKq4XKF3fO
  hosts:
    clickhouse:
      ansible_user: root
      ansible_host: 192.82.67.228
      ansible_port: 22226
    minio:
      ansible_user: root
      ansible_host: 192.82.67.228
      ansible_port: 22229
  children:
    hardened:
      vars:
        luks_device_path: /dev/vda2
        luks_volume_name: datalake-secure
        luks_volume_mount_path: /mnt/secure
      hosts:
        spark-primary:
          ansible_user: root
          ansible_host: 192.82.67.228
          ansible_port: 22220
        hadoop-yarn:
          ansible_user: root
          ansible_host: 192.82.67.228
          ansible_port: 22221
        airflow:
          ansible_user: root
          ansible_host: 192.82.67.228
          ansible_port: 22222
        atlas:
          ansible_user: root
          ansible_host: 192.82.67.228
          ansible_port: 22223
        spark-worker1:
          ansible_user: root
          ansible_host: 192.82.67.228
          ansible_port: 22224
        spark-worker2:
          ansible_user: root
          ansible_host: 192.82.67.228
          ansible_port: 22225
        config:
          ansible_user: root
          ansible_host: 192.82.67.228
          ansible_port: 22227
        source-control:
          ansible_user: root
          ansible_host: 192.82.67.228
          ansible_port: 22228
