all:
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: secrets/ansible.pem
    ansible_become_password: "{{ lookup('password', 'secrets/ansible_user_password', length=24) }}"
    sudo_user: unitel
    sudo_user_public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICHAWq/N8I40Ng6j3z55QtrP00LQzYcPlxuKq4XKF3fO
    admin_users:
      - name: oleg
        ssh_public_key: "{{ lookup('file', 'files/oleg.pub') }}"
      - name: tulgaa
        ssh_public_key: "{{ lookup('file', 'files/tulgaa.pub') }}"
      - name: erdenebayar
        ssh_public_key: "{{ lookup('file', 'files/erdenebayar.pub') }}"
      - name: ansible
        ssh_public_key: "{{ lookup('file', 'files/ansible.pub') }}"
        password: "{{ lookup('password',  'secrets/ansible_user_password', length=24, encrypt='sha512_crypt') }}"
  hosts:
    clickhouse:
      ansible_host: 192.82.67.228
      ansible_port: 22226
    minio:
      ansible_host: 192.82.67.228
      ansible_port: 22229
  children:
    hardened:
      vars:
        luks_volume_name: datalake-secure
        luks_volume_mount_path: /mnt/secure
      children:
        encrypted_lvm:
          vars:
            vg_name: datalake-vg
            lv_name: datalake-lv # lv stands for logical volume in LVM
            luks_device_path: /dev/vdb
            lvm_pvs: # PV stands for physical volume in LVM
              - /dev/vda2
              - /dev/vdb
          hosts:
            airflow:
              ansible_host: 192.82.67.228
              ansible_port: 22222
            atlas:
              ansible_host: 192.82.67.228
              ansible_port: 22223
            spark-primary:
              ansible_host: 192.82.67.228
              ansible_port: 22220
            spark-worker1:
              ansible_host: 192.82.67.228
              ansible_port: 22224
            spark-worker2:
              ansible_host: 192.82.67.228
              ansible_port: 22225
        encrypted_volume:
          vars:
            luks_device_path: /dev/vda2
          hosts:
            hadoop-yarn:
              ansible_host: 192.82.67.228
              ansible_port: 22221
            config:
              ansible_host: 192.82.67.228
              ansible_port: 22227
            source-control:
              ansible_host: 192.82.67.228
              ansible_port: 22228
