---
- name: Unmount encrypted partition
  hosts: hardened
  vars_prompt:
    - name: passphrase
      prompt: Enter passphrase for LUKS partition
      private: yes
  tasks:
    - name: Disallow user to run sudo
      become: true
      community.general.sudoers:
        name: "{{ sudo_user }}-root"
        user: "{{ sudo_user }}"
        nopassword: false
        commands: ALL
        state: absent
    - name: Open LUKS partition
      become: true
      community.crypto.luks_device:
        device: "{{ secure_volume_path }}"
        passphrase: "{{ passphrase }}"
        name: "{{ secure_volume_name }}"
        state: opened
    - name: Mount secure partition
      become: true
      mount:
        src: "/dev/mapper/{{ secure_volume_name }}"
        path: "{{ secure_volume_path }}"
        fstype: ext4
        state: mounted
    - name: Start Docker services
      become: true
      service:
        name: "{{ item }}"
        state: started
      loop:
        - docker
        - docker.socket
        - containerd
