---
- name: Create a admin users
  hosts: all
  tasks:
    - name: Create datalake group
      become: true
      group:
        name: datalake
        state: present
    - name: Create a admin user
      become: true
      user:
        name: "{{ item.name }}"
        shell: /bin/bash
        state: present
        group: datalake
        password: "{{ item.password | default('none') }}"
      with_items: "{{ admin_users }}"
    - name: Add public key to the admin user
      become: true
      authorized_key:
        user: "{{ item.name }}"
        state: present
        key: "{{ item.ssh_public_key }}"
      with_items: "{{ admin_users }}"
    - name: Configure sudo permissions
      become: true
      community.general.sudoers:
        name: "{{ item.name }}"
        user: "{{ item.name }}"
        nopassword: "{{ item.password is not defined }}"
        commands: ALL
        state: present
      with_items: "{{ admin_users }}"
    - name: Disable root login for SSH
      become: true
      lineinfile:
        path: /etc/ssh/sshd_config.d/001-disable-root-login.conf
        line: "PermitRootLogin no"
        state: present
        create: true
      notify: Restart SSHd
    - name: Disable password authentication for SSH
      become: true
      lineinfile:
        path: /etc/ssh/sshd_config.d/002-disable-password-auth.conf
        line: "PasswordAuthentication no"
        state: present
        create: true
      notify: Restart SSHd
  handlers:
    - name: Restart SSHd
      become: true
      service:
        name: sshd
        state: restarted
        enabled: true
