---
- name: Create a sudo user
  hosts: all
  vars:
    sudo_user: unitel
  vars_prompt:
    - name: sudo_user_password
      prompt: "Enter password for the sudo user {{ sudo_user }}"
      private: true
  tasks:
    - name: Create a sudo user
      become: true
      user:
        name: "{{ sudo_user }}"
        shell: /bin/bash
        password: "{{ sudo_user_password | password_hash('sha512') }}"
        state: present
    - name: Add public key to the sudo user
      become: true
      authorized_key:
        user: "{{ sudo_user }}"
        state: present
        key: "{{ sudo_user_public_key }}"
    - name: Allow user to run sudo with a password
      become: true
      community.general.sudoers:
        name: "{{ sudo_user }}-root"
        user: "{{ sudo_user }}"
        nopassword: false
        commands: ALL
        state: present
