---
- name: Unmount encrypted partition
  hosts: hardened
  tasks:
    - name: Stop Docker services
      become: true
      service:
        name: "{{ item }}"
        state: stopped
      loop:
        - docker
        - docker.socket
        - containerd
    - name: Unmount secure partition
      become: true
      mount:
        path: "{{ luks_volume_mount_path }}"
        state: unmounted
    - name: Unload LUKS partition
      become: true
      community.crypto.luks_device:
        name: "{{ luks_volume_name }}"
        state: absent
