# See: https://docs.docker.com/engine/install/ubuntu/
- name: Add GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker repository
  become: true
  vars:
    arch:
      aarch64: arm64
      x86_64: amd64
  apt_repository:
    repo: deb [arch={{ arch[ansible_architecture] }}] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present
- name: Update apt cache
  become: true
  apt:
    update_cache: yes
